sitename:"Hideto Koizumi"
markdown: kramdown

title: Hideto Koizumi's academic personal webpage
email: koizumi@iir.hit-u.ac.jp
tagline: Hideto Koizumi, hideto koizumi, economics, innovation, Hitotsubashi
description: Hideto Koizumi's academic webpage
url: "https://hidetokoizumi.github.io/index.html"

github_username:hidetokoizumi
author: Hideto Koizumi
google_site_verification

plugins:
  - jekyll-feed
plugins:
 - jekyll-sitemap
